<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE student [
   <!ELEMENT student (firstName,lastName,email,mobile)>
   <!ELEMENT firstName (#PCDATA)>
   <!ELEMENT lastName (#PCDATA)>
   <!ELEMENT email (#PCDATA)>
   <!ELEMENT mobile (#PCDATA)>
]>
<student>
  <firstName>John</firstName>
  <lastName>Smith</lastName>
  <email>jsmith@gmail.com</email>
  <mobile>0211223344</mobile>
</student>